---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-commit: 6211f2a930ea4e3eba7e5539b4e13fa4af65ef1e
    fabric8.io/git-branch: main
    fabric8.io/git-url: https://github.com/kei2701/DTDM.git
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/CurrencyExchange
    fabric8.io/scm-tag: HEAD
  labels:
    app: CurrencyExchange
    provider: fabric8
    version: 1.0.0
    group: com
  name: currencyexchange
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: CurrencyExchange
    provider: fabric8
    group: com
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 6211f2a930ea4e3eba7e5539b4e13fa4af65ef1e
        fabric8.io/git-branch: main
        fabric8.io/scm-tag: HEAD
        fabric8.io/git-url: https://github.com/kei2701/DTDM.git
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/CurrencyExchange
      labels:
        app: CurrencyExchange
        provider: fabric8
        version: 1.0.0
        group: com
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: currencyexchange:1.0.0
        imagePullPolicy: IfNotPresent
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - spring-boot
      from:
        kind: ImageStreamTag
        name: currencyexchange:1.0.0
    type: ImageChange
